"""empty message

Revision ID: 169cb795b730
Revises: 73d62992f206
Create Date: 2018-04-05 01:22:38.302543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '169cb795b730'
down_revision = '73d62992f206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient_datas', 'sharing_ipd',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sponsors', 'class',
               existing_type=postgresql.ENUM('NIH', 'US', 'INDUSTRY', 'OTHER', name='agencyclasstype'),
               nullable=False)
    op.alter_column('studies', 'eligibility_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('studies', 'oversight_info_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('studies', 'responsible_party_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('studies', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('studies', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('studies', 'responsible_party_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('studies', 'oversight_info_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('studies', 'eligibility_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('sponsors', 'class',
               existing_type=postgresql.ENUM('NIH', 'US', 'INDUSTRY', 'OTHER', name='agencyclasstype'),
               nullable=True)
    op.alter_column('patient_datas', 'sharing_ipd',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
