"""empty message

Revision ID: 32666f07308c
Revises:
Create Date: 2018-04-08 11:22:55.172206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32666f07308c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aliases',
    sa.Column('alias_id', sa.BigInteger(), nullable=False),
    sa.Column('alias', sa.Unicode(), nullable=False),
    sa.Column('md5', sa.Binary(), nullable=False),
    sa.PrimaryKeyConstraint('alias_id', name=op.f('pk_aliases')),
    schema='clinicaltrials'
    )
    op.create_index(op.f('ix_clinicaltrials_aliases_md5'), 'aliases', ['md5'], unique=True, schema='clinicaltrials')
    op.create_table('analyses',
    sa.Column('analysis_id', sa.BigInteger(), nullable=False),
    sa.Column('groups_desc', sa.Unicode(), nullable=True),
    sa.Column('non_inferiority_type', sa.Enum('SUPERIORITY', 'NON_INFERIORITY', 'EQUIVALENCE', 'OTHER', name='noninferioritytype'), nullable=True),
    sa.Column('non_inferiority_desc', sa.Unicode(), nullable=True),
    sa.Column('p_value', sa.Unicode(), nullable=True),
    sa.Column('p_value_desc', sa.Unicode(), nullable=True),
    sa.Column('method', sa.Unicode(), nullable=True),
    sa.Column('method_desc', sa.Unicode(), nullable=True),
    sa.Column('param_type', sa.Unicode(), nullable=True),
    sa.Column('param_value', sa.Unicode(), nullable=True),
    sa.Column('dispersion_type', sa.Enum('SD', 'SEM', name='analysisdispersiontype'), nullable=True),
    sa.Column('dispersion_value', sa.Unicode(), nullable=True),
    sa.Column('ci_percent', sa.Float(), nullable=True),
    sa.Column('ci_n_sides', sa.Enum('ONE', 'TWO', name='numsidestype'), nullable=True),
    sa.Column('ci_lower_limit', sa.Unicode(), nullable=True),
    sa.Column('ci_upper_limit', sa.Unicode(), nullable=True),
    sa.Column('ci_upper_limit_na_comment', sa.Unicode(), nullable=True),
    sa.Column('estimate_desc', sa.Unicode(), nullable=True),
    sa.Column('other_analysis_desc', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('analysis_id', name=op.f('pk_analyses')),
    schema='clinicaltrials'
    )
    op.create_index(op.f('ix_clinicaltrials_analyses_dispersion_type'), 'analyses', ['dispersion_type'], unique=False, schema='clinicaltrials')
    op.create_index(op.f('ix_clinicaltrials_analyses_non_inferiority_type'), 'analyses', ['non_inferiority_type'], unique=False, schema='clinicaltrials')
    op.create_table('arm_groups',
    sa.Column('arm_group_id', sa.BigInteger(), nullable=False),
    sa.Column('label', sa.Unicode(), nullable=False),
    sa.Column('type', sa.Unicode(), nullable=True),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('arm_group_id', name=op.f('pk_arm_groups')),
    schema='clinicaltrials'
    )
    op.create_table('baselines',
    sa.Column('baseline_id', sa.BigInteger(), nullable=False),
    sa.Column('population', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('baseline_id', name=op.f('pk_baselines')),
    schema='clinicaltrials'
    )
    op.create_table('conditions',
    sa.Column('condition_id', sa.BigInteger(), nullable=False),
    sa.Column('condition', sa.Unicode(), nullable=False),
    sa.Column('md5', sa.Binary(), nullable=False),
    sa.PrimaryKeyConstraint('condition_id', name=op.f('pk_conditions')),
    schema='clinicaltrials'
    )
    op.create_index(op.f('ix_clinicaltrials_conditions_condition'), 'conditions', ['condition'], unique=True, schema='clinicaltrials')
    op.create_index(op.f('ix_clinicaltrials_conditions_md5'), 'conditions', ['md5'], unique=True, schema='clinicaltrials')
    op.create_table('drop_withdraw_reasons',
    sa.Column('drop_withdraw_reason_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('drop_withdraw_reason_id', name=op.f('pk_drop_withdraw_reasons')),
    schema='clinicaltrials'
    )
    op.create_table('eligibilities',
    sa.Column('eligibility_id', sa.BigInteger(), nullable=False),
    sa.Column('study_pop', sa.UnicodeText(), nullable=True),
    sa.Column('sampling_method', sa.Enum('PROBABILITY', 'NON_PROBABILITY', name='samplingmethodtype'), nullable=True),
    sa.Column('criteria', sa.UnicodeText(), nullable=True),
    sa.Column('gender', sa.Enum('FEMALE', 'MALE', 'ALL', name='gendertype'), nullable=True),
    sa.Column('gender_based', sa.Boolean(), nullable=True),
    sa.Column('gender_description', sa.Unicode(), nullable=True),
    sa.Column('minimum_age', sa.Unicode(), nullable=True),
    sa.Column('maximum_age', sa.Unicode(), nullable=True),
    sa.Column('healthy_volunteers', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('eligibility_id', name=op.f('pk_eligibilities')),
    schema='clinicaltrials'
    )
    op.create_table('enrollments',
    sa.Column('enrollment_id', sa.BigInteger(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('ACTUAL', 'ANTICIPATED', 'ESTIMATE', name='actualtype'), nullable=True),
    sa.PrimaryKeyConstraint('enrollment_id', name=op.f('pk_enrollments')),
    schema='clinicaltrials'
    )
    op.create_table('event_categories',
    sa.Column('event_category_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('event_category_id', name=op.f('pk_event_categories')),
    schema='clinicaltrials'
    )
    op.create_table('event_lists',
    sa.Column('event_list_id', sa.BigInteger(), nullable=False),
    sa.Column('frequency_threshold', sa.Unicode(), nullable=True),
    sa.Column('default_vocab', sa.Unicode(), nullable=True),
    sa.Column('default_assessment', sa.Enum('SYSTEMATIC', 'NON_SYSTEMATIC', name='eventassessmenttype'), nullable=True),
    sa.PrimaryKeyConstraint('event_list_id', name=op.f('pk_event_lists')),
    schema='clinicaltrials'
    )
    op.create_index(op.f('ix_clinicaltrials_event_lists_default_assessment'), 'event_lists', ['default_assessment'], unique=False, schema='clinicaltrials')
    op.create_table('events',
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('sub_title', sa.Unicode(), nullable=True),
    sa.Column('assessment', sa.Enum('SYSTEMATIC', 'NON_SYSTEMATIC', name='eventassessmenttype'), nullable=True),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_events')),
    schema='clinicaltrials'
    )
    op.create_index(op.f('ix_clinicaltrials_events_assessment'), 'events', ['assessment'], unique=False, schema='clinicaltrials')
    op.create_table('expanded_access_infos',
    sa.Column('expanded_access_info_id', sa.BigInteger(), nullable=False),
    sa.Column('individual', sa.Boolean(), nullable=True),
    sa.Column('intermediate', sa.Boolean(), nullable=True),
    sa.Column('treatment', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('expanded_access_info_id', name=op.f('pk_expanded_access_infos')),
    schema='clinicaltrials'
    )
    op.create_table('facilities',
    sa.Column('facility_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('city', sa.Unicode(), nullable=True),
    sa.Column('state', sa.Unicode(), nullable=True),
    sa.Column('zip_code', sa.Unicode(), nullable=True),
    sa.Column('country', sa.Unicode(), nullable=True),
    sa.Column('md5', sa.Binary(), nullable=False),
    sa.PrimaryKeyConstraint('facility_id', name=op.f('pk_facilities')),
    schema='clinicaltrials'
    )
    op.create_index(op.f('ix_clinicaltrials_facilities_md5'), 'facilities', ['md5'], unique=True, schema='clinicaltrials')
    op.create_table('groups',
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('identifier', sa.Unicode(), nullable=False),
    sa.Column('title', sa.Unicode(), nullable=True),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('group_id', name=op.f('pk_groups')),
    schema='clinicaltrials'
    )
    op.create_table('interventions',
    sa.Column('intervention_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('BEHAVIORAL', 'BIOLOGICAL', 'COMBINATION', 'DEVICE', 'DIAGNOSTIC', 'DIETARY', 'DRUG', 'GENETIC', 'PROCEDURE', 'RADIATION', 'OTHER', name='interventiontype'), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('intervention_id', name=op.f('pk_interventions')),
    schema='clinicaltrials'
    )
    op.create_table('keywords',
    sa.Column('keyword_id', sa.BigInteger(), nullable=False),
    sa.Column('keyword', sa.Unicode(), nullable=False),
    sa.Column('md5', sa.Binary(), nullable=False),
    sa.PrimaryKeyConstraint('keyword_id', name=op.f('pk_keywords')),
    schema='clinicaltrials'
    )
    op.create_index(op.f('ix_clinicaltrials_keywords_keyword'), 'keywords', ['keyword'], unique=True, schema='clinicaltrials')
    op.create_index(op.f('ix_clinicaltrials_keywords_md5'), 'keywords', ['md5'], unique=True, schema='clinicaltrials')
    op.create_table('measure_analyzeds',
    sa.Column('measure_analyzed_id', sa.BigInteger(), nullable=False),
    sa.Column('units', sa.Unicode(), nullable=True),
    sa.Column('scope', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('measure_analyzed_id', name=op.f('pk_measure_analyzeds')),
    schema='clinicaltrials'
    )
    op.create_table('measure_categories',
    sa.Column('measure_category_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('measure_category_id', name=op.f('pk_measure_categories')),
    schema='clinicaltrials'
    )
    op.create_table('measure_classes',
    sa.Column('measure_class_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('measure_class_id', name=op.f('pk_measure_classes')),
    schema='clinicaltrials'
    )
    op.create_table('measures',
    sa.Column('measure_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Unicode(), nullable=False),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.Column('population', sa.Unicode(), nullable=True),
    sa.Column('units', sa.Unicode(), nullable=True),
    sa.Column('parameter', sa.Enum('GEOMETRIC', 'GLS_MEAN', 'LS_MEAN', 'LOG_MEAN', 'MEAN', 'MEDIAN', 'NUMBER', 'PARTICIPANTS', 'UNITS', name='measureparametertype'), nullable=False),
    sa.Column('dispersion', sa.Unicode(), nullable=True),
    sa.Column('units_analyzed', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('measure_id', name=op.f('pk_measures')),
    schema='clinicaltrials'
    )
    op.create_table('mesh_terms',
    sa.Column('mesh_term_id', sa.BigInteger(), nullable=False),
    sa.Column('term', sa.Unicode(), nullable=False),
    sa.Column('md5', sa.Binary(), nullable=False),
    sa.PrimaryKeyConstraint('mesh_term_id', name=op.f('pk_mesh_terms')),
    schema='clinicaltrials'
    )
    op.create_index(op.f('ix_clinicaltrials_mesh_terms_md5'), 'mesh_terms', ['md5'], unique=True, schema='clinicaltrials')
    op.create_table('milestones',
    sa.Column('milestone_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('milestone_id', name=op.f('pk_milestones')),
    schema='clinicaltrials'
    )
    op.create_table('oversight_infos',
    sa.Column('oversight_info_id', sa.BigInteger(), nullable=False),
    sa.Column('has_dmc', sa.Boolean(), nullable=True),
    sa.Column('is_fda_regulated_drug', sa.Boolean(), nullable=True),
    sa.Column('is_fda_regulated_device', sa.Boolean(), nullable=True),
    sa.Column('is_unapproved_device', sa.Boolean(), nullable=True),
    sa.Column('is_ppsd', sa.Boolean(), nullable=True),
    sa.Column('is_us_export', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('oversight_info_id', name=op.f('pk_oversight_infos')),
    schema='clinicaltrials'
    )
    op.create_table('participant_flows',
    sa.Column('participant_flow_id', sa.BigInteger(), nullable=False),
    sa.Column('recruitment_details', sa.Unicode(), nullable=True),
    sa.Column('pre_assignment_details', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('participant_flow_id', name=op.f('pk_participant_flows')),
    schema='clinicaltrials'
    )
    op.create_table('patient_datas',
    sa.Column('patient_data_id', sa.BigInteger(), nullable=False),
    sa.Column('sharing_ipd', sa.Unicode(), nullable=False),
    sa.Column('ipd_description', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('patient_data_id', name=op.f('pk_patient_datas')),
    schema='clinicaltrials'
    )
    op.create_table('periods',
    sa.Column('period_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Unicode(), nullable=False),
    sa.PrimaryKeyConstraint('period_id', name=op.f('pk_periods')),
    schema='clinicaltrials'
    )
    op.create_table('persons',
    sa.Column('person_id', sa.BigInteger(), nullable=False),
    sa.Column('name_first', sa.Unicode(), nullable=True),
    sa.Column('name_middle', sa.Unicode(), nullable=True),
    sa.Column('name_last', sa.Unicode(), nullable=True),
    sa.Column('degrees', sa.Unicode(), nullable=True),
    sa.Column('md5', sa.Binary(), nullable=False),
    sa.PrimaryKeyConstraint('person_id', name=op.f('pk_persons')),
    schema='clinicaltrials'
    )
    op.create_index(op.f('ix_clinicaltrials_persons_md5'), 'persons', ['md5'], unique=True, schema='clinicaltrials')
    op.create_table('protocol_outcomes',
    sa.Column('protocol_outcome_id', sa.BigInteger(), nullable=False),
    sa.Column('measure', sa.Unicode(), nullable=False),
    sa.Column('time_frame', sa.Unicode(), nullable=True),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('protocol_outcome_id', name=op.f('pk_protocol_outcomes')),
    schema='clinicaltrials'
    )
    op.create_table('references',
    sa.Column('reference_id', sa.BigInteger(), nullable=False),
    sa.Column('citation', sa.Unicode(), nullable=True),
    sa.Column('pmid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('reference_id', name=op.f('pk_references')),
    sa.UniqueConstraint('pmid', name=op.f('uq_references_pmid')),
    schema='clinicaltrials'
    )
    op.create_table('responsible_parties',
    sa.Column('responsible_party_id', sa.BigInteger(), nullable=False),
    sa.Column('name_title', sa.Unicode(), nullable=True),
    sa.Column('organization', sa.Unicode(), nullable=True),
    sa.Column('type', sa.Enum('SPONSOR', 'PRINCIPAL', 'SPONSOR_INVESTIGATOR', name='responsiblepartytype'), nullable=True),
    sa.Column('investigator_affiliation', sa.Unicode(), nullable=True),
    sa.Column('investigator_full_name', sa.Unicode(), nullable=True),
    sa.Column('investigator_title', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('responsible_party_id', name=op.f('pk_responsible_parties')),
    schema='clinicaltrials'
    )
    op.create_table('sponsors',
    sa.Column('sponsor_id', sa.BigInteger(), nullable=False),
    sa.Column('agency', sa.Unicode(), nullable=False),
    sa.Column('class', sa.Enum('NIH', 'US', 'INDUSTRY', 'OTHER', name='agencyclasstype'), nullable=False),
    sa.Column('md5', sa.Binary(), nullable=False),
    sa.PrimaryKeyConstraint('sponsor_id', name=op.f('pk_sponsors')),
    schema='clinicaltrials'
    )
    op.create_index(op.f('ix_clinicaltrials_sponsors_class'), 'sponsors', ['class'], unique=False, schema='clinicaltrials')
    op.create_index(op.f('ix_clinicaltrials_sponsors_md5'), 'sponsors', ['md5'], unique=True, schema='clinicaltrials')
    op.create_table('study_dates',
    sa.Column('study_dates_id', sa.BigInteger(), nullable=False),
    sa.Column('study_first_submitted', sa.Date(), nullable=True),
    sa.Column('study_first_submitted_qc', sa.Date(), nullable=True),
    sa.Column('study_first_posted', sa.Date(), nullable=True),
    sa.Column('results_first_submitted', sa.Date(), nullable=True),
    sa.Column('results_first_submitted_qc', sa.Date(), nullable=True),
    sa.Column('results_first_posted', sa.Date(), nullable=True),
    sa.Column('disposition_first_submitted', sa.Date(), nullable=True),
    sa.Column('disposition_first_submitted_qc', sa.Date(), nullable=True),
    sa.Column('disposition_first_posted', sa.Date(), nullable=True),
    sa.Column('last_update_submitted', sa.Date(), nullable=True),
    sa.Column('last_update_submitted_qc', sa.Date(), nullable=True),
    sa.Column('last_update_posted', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('study_dates_id', name=op.f('pk_study_dates')),
    schema='clinicaltrials'
    )
    op.create_table('study_design_infos',
    sa.Column('study_design_info_id', sa.BigInteger(), nullable=False),
    sa.Column('allocation', sa.Unicode(), nullable=True),
    sa.Column('intervention_model', sa.Unicode(), nullable=True),
    sa.Column('intervention_model_description', sa.Unicode(), nullable=True),
    sa.Column('primary_purpose', sa.Unicode(), nullable=True),
    sa.Column('observational_model', sa.Unicode(), nullable=True),
    sa.Column('time_perspective', sa.Unicode(), nullable=True),
    sa.Column('masking', sa.Unicode(), nullable=True),
    sa.Column('masking_description', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('study_design_info_id', name=op.f('pk_study_design_infos')),
    schema='clinicaltrials'
    )
    op.create_table('study_docs',
    sa.Column('study_doc_id', sa.BigInteger(), nullable=False),
    sa.Column('doc_id', sa.Unicode(), nullable=True),
    sa.Column('doc_type', sa.Unicode(), nullable=True),
    sa.Column('doc_url', sa.Unicode(), nullable=True),
    sa.Column('doc_comment', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('study_doc_id', name=op.f('pk_study_docs')),
    schema='clinicaltrials'
    )
    op.create_table('analysis_groups',
    sa.Column('analysis_group_id', sa.BigInteger(), nullable=False),
    sa.Column('analysis_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['clinicaltrials.analyses.analysis_id'], name=op.f('fk_analysis_groups_analysis_id_analyses')),
    sa.ForeignKeyConstraint(['group_id'], ['clinicaltrials.groups.group_id'], name=op.f('fk_analysis_groups_group_id_groups')),
    sa.PrimaryKeyConstraint('analysis_group_id', name=op.f('pk_analysis_groups')),
    sa.UniqueConstraint('analysis_id', 'group_id', name=op.f('uq_analysis_groups_analysis_id'))
    )
    op.create_table('baseline_groups',
    sa.Column('baseline_group_id', sa.BigInteger(), nullable=False),
    sa.Column('baseline_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['baseline_id'], ['clinicaltrials.baselines.baseline_id'], name=op.f('fk_baseline_groups_baseline_id_baselines')),
    sa.ForeignKeyConstraint(['group_id'], ['clinicaltrials.groups.group_id'], name=op.f('fk_baseline_groups_group_id_groups')),
    sa.PrimaryKeyConstraint('baseline_group_id', name=op.f('pk_baseline_groups')),
    sa.UniqueConstraint('baseline_id', 'group_id', name=op.f('uq_baseline_groups_baseline_id')),
    schema='clinicaltrials'
    )
    op.create_table('baseline_measure_analyzeds',
    sa.Column('baseline_measure_analyzed_id', sa.BigInteger(), nullable=False),
    sa.Column('baseline_id', sa.BigInteger(), nullable=False),
    sa.Column('measure_analyzed_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['baseline_id'], ['clinicaltrials.baselines.baseline_id'], name=op.f('fk_baseline_measure_analyzeds_baseline_id_baselines')),
    sa.ForeignKeyConstraint(['measure_analyzed_id'], ['clinicaltrials.measure_analyzeds.measure_analyzed_id'], name=op.f('fk_baseline_measure_analyzeds_measure_analyzed_id_measure_analyzeds')),
    sa.PrimaryKeyConstraint('baseline_measure_analyzed_id', name=op.f('pk_baseline_measure_analyzeds')),
    sa.UniqueConstraint('baseline_id', 'measure_analyzed_id', name=op.f('uq_baseline_measure_analyzeds_baseline_id')),
    schema='clinicaltrials'
    )
    op.create_table('baseline_measures',
    sa.Column('baseline_measure_id', sa.BigInteger(), nullable=False),
    sa.Column('baseline_id', sa.BigInteger(), nullable=False),
    sa.Column('measure_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['baseline_id'], ['clinicaltrials.baselines.baseline_id'], name=op.f('fk_baseline_measures_baseline_id_baselines')),
    sa.ForeignKeyConstraint(['measure_id'], ['clinicaltrials.measures.measure_id'], name=op.f('fk_baseline_measures_measure_id_measures')),
    sa.PrimaryKeyConstraint('baseline_measure_id', name=op.f('pk_baseline_measures')),
    sa.UniqueConstraint('baseline_id', 'measure_id', name=op.f('uq_baseline_measures_baseline_id')),
    schema='clinicaltrials'
    )
    op.create_table('contacts',
    sa.Column('contact_id', sa.BigInteger(), nullable=False),
    sa.Column('person_id', sa.BigInteger(), nullable=False),
    sa.Column('phone', sa.Unicode(), nullable=True),
    sa.Column('phone_ext', sa.Unicode(), nullable=True),
    sa.Column('email', sa.Unicode(), nullable=True),
    sa.Column('md5', sa.Binary(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['clinicaltrials.persons.person_id'], name=op.f('fk_contacts_person_id_persons')),
    sa.PrimaryKeyConstraint('contact_id', name=op.f('pk_contacts')),
    schema='clinicaltrials'
    )
    op.create_index(op.f('ix_clinicaltrials_contacts_md5'), 'contacts', ['md5'], unique=True, schema='clinicaltrials')
    op.create_table('event_category_events',
    sa.Column('event_category_event_id', sa.BigInteger(), nullable=False),
    sa.Column('event_category_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['event_category_id'], ['clinicaltrials.event_categories.event_category_id'], name=op.f('fk_event_category_events_event_category_id_event_categories')),
    sa.ForeignKeyConstraint(['event_id'], ['clinicaltrials.events.event_id'], name=op.f('fk_event_category_events_event_id_events')),
    sa.PrimaryKeyConstraint('event_category_event_id', name=op.f('pk_event_category_events')),
    sa.UniqueConstraint('event_category_id', 'event_id', name=op.f('uq_event_category_events_event_category_id')),
    schema='clinicaltrials'
    )
    op.create_table('event_counts',
    sa.Column('event_count_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('subjects_affected', sa.Integer(), nullable=True),
    sa.Column('subjects_at_risk', sa.Integer(), nullable=True),
    sa.Column('events', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['clinicaltrials.groups.group_id'], name=op.f('fk_event_counts_group_id_groups')),
    sa.PrimaryKeyConstraint('event_count_id', name=op.f('pk_event_counts')),
    schema='clinicaltrials'
    )
    op.create_table('event_list_categories',
    sa.Column('event_list_category_id', sa.BigInteger(), nullable=False),
    sa.Column('event_list_id', sa.BigInteger(), nullable=False),
    sa.Column('event_category_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['event_category_id'], ['clinicaltrials.event_categories.event_category_id'], name=op.f('fk_event_list_categories_event_category_id_event_categories')),
    sa.ForeignKeyConstraint(['event_list_id'], ['clinicaltrials.event_lists.event_list_id'], name=op.f('fk_event_list_categories_event_list_id_event_lists')),
    sa.PrimaryKeyConstraint('event_list_category_id', name=op.f('pk_event_list_categories')),
    sa.UniqueConstraint('event_list_id', 'event_category_id', name=op.f('uq_event_list_categories_event_list_id')),
    schema='clinicaltrials'
    )
    op.create_table('intervention_aliases',
    sa.Column('intervention_alias_id', sa.BigInteger(), nullable=False),
    sa.Column('intervention_id', sa.BigInteger(), nullable=False),
    sa.Column('alias_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['alias_id'], ['clinicaltrials.aliases.alias_id'], name=op.f('fk_intervention_aliases_alias_id_aliases')),
    sa.ForeignKeyConstraint(['intervention_id'], ['clinicaltrials.interventions.intervention_id'], name=op.f('fk_intervention_aliases_intervention_id_interventions')),
    sa.PrimaryKeyConstraint('intervention_alias_id', name=op.f('pk_intervention_aliases')),
    sa.UniqueConstraint('intervention_id', 'alias_id', name=op.f('uq_intervention_aliases_intervention_id')),
    schema='clinicaltrials'
    )
    op.create_table('intervention_arm_groups',
    sa.Column('intervention_arm_group_id', sa.BigInteger(), nullable=False),
    sa.Column('intervention_id', sa.BigInteger(), nullable=False),
    sa.Column('arm_group_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['arm_group_id'], ['clinicaltrials.arm_groups.arm_group_id'], name=op.f('fk_intervention_arm_groups_arm_group_id_arm_groups')),
    sa.ForeignKeyConstraint(['intervention_id'], ['clinicaltrials.interventions.intervention_id'], name=op.f('fk_intervention_arm_groups_intervention_id_interventions')),
    sa.PrimaryKeyConstraint('intervention_arm_group_id', name=op.f('pk_intervention_arm_groups')),
    sa.UniqueConstraint('intervention_id', 'arm_group_id', name=op.f('uq_intervention_arm_groups_intervention_id')),
    schema='clinicaltrials'
    )
    op.create_table('investigators',
    sa.Column('investigator_id', sa.BigInteger(), nullable=False),
    sa.Column('person_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('PRINCIPAL', 'SUB', 'CHAIR', 'DIRECTOR', name='roletype'), nullable=True),
    sa.Column('affiliation', sa.Unicode(), nullable=True),
    sa.Column('md5', sa.Binary(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['clinicaltrials.persons.person_id'], name=op.f('fk_investigators_person_id_persons')),
    sa.PrimaryKeyConstraint('investigator_id', name=op.f('pk_investigators')),
    schema='clinicaltrials'
    )
    op.create_index(op.f('ix_clinicaltrials_investigators_md5'), 'investigators', ['md5'], unique=True, schema='clinicaltrials')
    op.create_index(op.f('ix_clinicaltrials_investigators_role'), 'investigators', ['role'], unique=False, schema='clinicaltrials')
    op.create_table('measure_class_analyzeds',
    sa.Column('measure_class_analyzed_id', sa.BigInteger(), nullable=False),
    sa.Column('measure_class_id', sa.BigInteger(), nullable=False),
    sa.Column('measure_analyzed_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['measure_analyzed_id'], ['clinicaltrials.measure_analyzeds.measure_analyzed_id'], name=op.f('fk_measure_class_analyzeds_measure_analyzed_id_measure_analyzeds')),
    sa.ForeignKeyConstraint(['measure_class_id'], ['clinicaltrials.measure_classes.measure_class_id'], name=op.f('fk_measure_class_analyzeds_measure_class_id_measure_classes')),
    sa.PrimaryKeyConstraint('measure_class_analyzed_id', name=op.f('pk_measure_class_analyzeds')),
    schema='clinicaltrials'
    )
    op.create_table('measure_class_categories',
    sa.Column('measure_class_category_id', sa.BigInteger(), nullable=False),
    sa.Column('measure_class_id', sa.BigInteger(), nullable=False),
    sa.Column('measure_category_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['measure_category_id'], ['clinicaltrials.measure_categories.measure_category_id'], name=op.f('fk_measure_class_categories_measure_category_id_measure_categories')),
    sa.ForeignKeyConstraint(['measure_class_id'], ['clinicaltrials.measure_classes.measure_class_id'], name=op.f('fk_measure_class_categories_measure_class_id_measure_classes')),
    sa.PrimaryKeyConstraint('measure_class_category_id', name=op.f('pk_measure_class_categories')),
    schema='clinicaltrials'
    )
    op.create_table('measure_counts',
    sa.Column('measure_count_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('value', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['clinicaltrials.groups.group_id'], name=op.f('fk_measure_counts_group_id_groups')),
    sa.PrimaryKeyConstraint('measure_count_id', name=op.f('pk_measure_counts')),
    schema='clinicaltrials'
    )
    op.create_table('measure_measure_analyzeds',
    sa.Column('measure_measure_analyzed_id', sa.BigInteger(), nullable=False),
    sa.Column('measure_id', sa.BigInteger(), nullable=False),
    sa.Column('measure_analyzed_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['measure_analyzed_id'], ['clinicaltrials.measure_analyzeds.measure_analyzed_id'], name=op.f('fk_measure_measure_analyzeds_measure_analyzed_id_measure_analyzeds')),
    sa.ForeignKeyConstraint(['measure_id'], ['clinicaltrials.measures.measure_id'], name=op.f('fk_measure_measure_analyzeds_measure_id_measures')),
    sa.PrimaryKeyConstraint('measure_measure_analyzed_id', name=op.f('pk_measure_measure_analyzeds')),
    schema='clinicaltrials'
    )
    op.create_table('measure_measure_classes',
    sa.Column('measure_measure_class_id', sa.BigInteger(), nullable=False),
    sa.Column('measure_id', sa.BigInteger(), nullable=False),
    sa.Column('measure_class_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['measure_class_id'], ['clinicaltrials.measure_classes.measure_class_id'], name=op.f('fk_measure_measure_classes_measure_class_id_measure_classes')),
    sa.ForeignKeyConstraint(['measure_id'], ['clinicaltrials.measures.measure_id'], name=op.f('fk_measure_measure_classes_measure_id_measures')),
    sa.PrimaryKeyConstraint('measure_measure_class_id', name=op.f('pk_measure_measure_classes')),
    schema='clinicaltrials'
    )
    op.create_table('measurements',
    sa.Column('measurement_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('value', sa.Unicode(), nullable=True),
    sa.Column('spread', sa.Unicode(), nullable=True),
    sa.Column('lower_limit', sa.Unicode(), nullable=True),
    sa.Column('upper_limit', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['clinicaltrials.groups.group_id'], name=op.f('fk_measurements_group_id_groups')),
    sa.PrimaryKeyConstraint('measurement_id', name=op.f('pk_measurements')),
    schema='clinicaltrials'
    )
    op.create_table('participant_flow_groups',
    sa.Column('participant_flow_group_id', sa.BigInteger(), nullable=False),
    sa.Column('participant_flow_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['clinicaltrials.groups.group_id'], name=op.f('fk_participant_flow_groups_group_id_groups')),
    sa.ForeignKeyConstraint(['participant_flow_id'], ['clinicaltrials.participant_flows.participant_flow_id'], name=op.f('fk_participant_flow_groups_participant_flow_id_participant_flows')),
    sa.PrimaryKeyConstraint('participant_flow_group_id', name=op.f('pk_participant_flow_groups')),
    sa.UniqueConstraint('participant_flow_id', 'group_id', name=op.f('uq_participant_flow_groups_participant_flow_id')),
    schema='clinicaltrials'
    )
    op.create_table('participant_flow_periods',
    sa.Column('participant_flow_period_id', sa.BigInteger(), nullable=False),
    sa.Column('participant_flow_id', sa.BigInteger(), nullable=False),
    sa.Column('period_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['participant_flow_id'], ['clinicaltrials.participant_flows.participant_flow_id'], name=op.f('fk_participant_flow_periods_participant_flow_id_participant_flows')),
    sa.ForeignKeyConstraint(['period_id'], ['clinicaltrials.periods.period_id'], name=op.f('fk_participant_flow_periods_period_id_periods')),
    sa.PrimaryKeyConstraint('participant_flow_period_id', name=op.f('pk_participant_flow_periods')),
    sa.UniqueConstraint('participant_flow_id', 'period_id', name=op.f('uq_participant_flow_periods_participant_flow_id')),
    schema='clinicaltrials'
    )
    op.create_table('participants',
    sa.Column('participant_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['clinicaltrials.groups.group_id'], name=op.f('fk_participants_group_id_groups')),
    sa.PrimaryKeyConstraint('participant_id', name=op.f('pk_participants')),
    schema='clinicaltrials'
    )
    op.create_table('period_drop_withdraw_reasons',
    sa.Column('period_drop_withdraw_reason_id', sa.BigInteger(), nullable=False),
    sa.Column('period_id', sa.BigInteger(), nullable=False),
    sa.Column('drop_withdraw_reason_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['drop_withdraw_reason_id'], ['clinicaltrials.drop_withdraw_reasons.drop_withdraw_reason_id'], name=op.f('fk_period_drop_withdraw_reasons_drop_withdraw_reason_id_drop_withdraw_reasons')),
    sa.ForeignKeyConstraint(['period_id'], ['clinicaltrials.periods.period_id'], name=op.f('fk_period_drop_withdraw_reasons_period_id_periods')),
    sa.PrimaryKeyConstraint('period_drop_withdraw_reason_id', name=op.f('pk_period_drop_withdraw_reasons')),
    sa.UniqueConstraint('period_id', 'drop_withdraw_reason_id', name=op.f('uq_period_drop_withdraw_reasons_period_id')),
    schema='clinicaltrials'
    )
    op.create_table('period_milestones',
    sa.Column('period_milestone_id', sa.BigInteger(), nullable=False),
    sa.Column('period_id', sa.BigInteger(), nullable=False),
    sa.Column('milestone_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['clinicaltrials.milestones.milestone_id'], name=op.f('fk_period_milestones_milestone_id_milestones')),
    sa.ForeignKeyConstraint(['period_id'], ['clinicaltrials.periods.period_id'], name=op.f('fk_period_milestones_period_id_periods')),
    sa.PrimaryKeyConstraint('period_milestone_id', name=op.f('pk_period_milestones')),
    sa.UniqueConstraint('period_id', 'milestone_id', name=op.f('uq_period_milestones_period_id')),
    schema='clinicaltrials'
    )
    op.create_table('reported_events',
    sa.Column('reported_event_id', sa.BigInteger(), nullable=False),
    sa.Column('time_frame', sa.Unicode(), nullable=True),
    sa.Column('desc', sa.Unicode(), nullable=True),
    sa.Column('serious_event_list_id', sa.BigInteger(), nullable=False),
    sa.Column('other_event_list_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['other_event_list_id'], ['clinicaltrials.event_lists.event_list_id'], name=op.f('fk_reported_events_other_event_list_id_event_lists')),
    sa.ForeignKeyConstraint(['serious_event_list_id'], ['clinicaltrials.event_lists.event_list_id'], name=op.f('fk_reported_events_serious_event_list_id_event_lists')),
    sa.PrimaryKeyConstraint('reported_event_id', name=op.f('pk_reported_events')),
    schema='clinicaltrials'
    )
    op.create_table('result_outcomes',
    sa.Column('result_outcome_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('PRIMARY', 'SECONDARY', 'POST_HOC', 'OTHER', name='outcometype'), nullable=False),
    sa.Column('title', sa.Unicode(), nullable=False),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.Column('time_frame', sa.Unicode(), nullable=True),
    sa.Column('safety_issue', sa.Boolean(), nullable=True),
    sa.Column('population', sa.Unicode(), nullable=True),
    sa.Column('measure_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['measure_id'], ['clinicaltrials.measures.measure_id'], name=op.f('fk_result_outcomes_measure_id_measures')),
    sa.PrimaryKeyConstraint('result_outcome_id', name=op.f('pk_result_outcomes')),
    schema='clinicaltrials'
    )
    op.create_table('event_event_counts',
    sa.Column('event_event_count_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('event_count_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['event_count_id'], ['clinicaltrials.event_counts.event_count_id'], name=op.f('fk_event_event_counts_event_count_id_event_counts')),
    sa.ForeignKeyConstraint(['event_id'], ['clinicaltrials.events.event_id'], name=op.f('fk_event_event_counts_event_id_events')),
    sa.PrimaryKeyConstraint('event_event_count_id', name=op.f('pk_event_event_counts')),
    sa.UniqueConstraint('event_id', 'event_count_id', name=op.f('uq_event_event_counts_event_id')),
    schema='clinicaltrials'
    )
    op.create_table('locations',
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('facility_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE_NOT', 'COMPLETED', 'INVITATION', 'NOT_YET', 'RECRUITING', 'SUSPENDED', 'TERMINATED', 'WITHDRAWN', name='recruitmentstatustype'), nullable=True),
    sa.Column('contact_primary_id', sa.BigInteger(), nullable=True),
    sa.Column('contact_backup_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['contact_backup_id'], ['clinicaltrials.contacts.contact_id'], name=op.f('fk_locations_contact_backup_id_contacts')),
    sa.ForeignKeyConstraint(['contact_primary_id'], ['clinicaltrials.contacts.contact_id'], name=op.f('fk_locations_contact_primary_id_contacts')),
    sa.ForeignKeyConstraint(['facility_id'], ['clinicaltrials.facilities.facility_id'], name=op.f('fk_locations_facility_id_facilities')),
    sa.PrimaryKeyConstraint('location_id', name=op.f('pk_locations')),
    sa.UniqueConstraint('facility_id', 'contact_primary_id', 'contact_backup_id', name=op.f('uq_locations_facility_id')),
    schema='clinicaltrials'
    )
    op.create_index(op.f('ix_clinicaltrials_locations_status'), 'locations', ['status'], unique=False, schema='clinicaltrials')
    op.create_table('measure_analyzed_counts',
    sa.Column('measure_analyzed_count_id', sa.BigInteger(), nullable=False),
    sa.Column('measure_analyzed_id', sa.BigInteger(), nullable=False),
    sa.Column('measure_count_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['measure_analyzed_id'], ['clinicaltrials.measure_analyzeds.measure_analyzed_id'], name=op.f('fk_measure_analyzed_counts_measure_analyzed_id_measure_analyzeds')),
    sa.ForeignKeyConstraint(['measure_count_id'], ['clinicaltrials.measure_counts.measure_count_id'], name=op.f('fk_measure_analyzed_counts_measure_count_id_measure_counts')),
    sa.PrimaryKeyConstraint('measure_analyzed_count_id', name=op.f('pk_measure_analyzed_counts')),
    schema='clinicaltrials'
    )
    op.create_table('measure_category_measurements',
    sa.Column('measure_category_measurement_id', sa.BigInteger(), nullable=False),
    sa.Column('measure_category_id', sa.BigInteger(), nullable=False),
    sa.Column('measurement_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['measure_category_id'], ['clinicaltrials.measure_categories.measure_category_id'], name=op.f('fk_measure_category_measurements_measure_category_id_measure_categories')),
    sa.ForeignKeyConstraint(['measurement_id'], ['clinicaltrials.measurements.measurement_id'], name=op.f('fk_measure_category_measurements_measurement_id_measurements')),
    sa.PrimaryKeyConstraint('measure_category_measurement_id', name=op.f('pk_measure_category_measurements')),
    schema='clinicaltrials'
    )
    op.create_table('milestone_participants',
    sa.Column('milestone_participant_id', sa.BigInteger(), nullable=False),
    sa.Column('milestone_id', sa.BigInteger(), nullable=False),
    sa.Column('participant_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['clinicaltrials.milestones.milestone_id'], name=op.f('fk_milestone_participants_milestone_id_milestones')),
    sa.ForeignKeyConstraint(['participant_id'], ['clinicaltrials.participants.participant_id'], name=op.f('fk_milestone_participants_participant_id_participants')),
    sa.PrimaryKeyConstraint('milestone_participant_id', name=op.f('pk_milestone_participants')),
    sa.UniqueConstraint('milestone_id', 'participant_id', name=op.f('uq_milestone_participants_milestone_id')),
    schema='clinicaltrials'
    )
    op.create_table('reported_event_groups',
    sa.Column('reported_event_group_id', sa.BigInteger(), nullable=False),
    sa.Column('reported_event_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['clinicaltrials.groups.group_id'], name=op.f('fk_reported_event_groups_group_id_groups')),
    sa.ForeignKeyConstraint(['reported_event_id'], ['clinicaltrials.reported_events.reported_event_id'], name=op.f('fk_reported_event_groups_reported_event_id_reported_events')),
    sa.PrimaryKeyConstraint('reported_event_group_id', name=op.f('pk_reported_event_groups')),
    sa.UniqueConstraint('reported_event_id', 'group_id', name=op.f('uq_reported_event_groups_reported_event_id')),
    schema='clinicaltrials'
    )
    op.create_table('result_outcome_groups',
    sa.Column('result_outcome_group_id', sa.BigInteger(), nullable=False),
    sa.Column('result_outcome_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['clinicaltrials.groups.group_id'], name=op.f('fk_result_outcome_groups_group_id_groups')),
    sa.ForeignKeyConstraint(['result_outcome_id'], ['clinicaltrials.result_outcomes.result_outcome_id'], name=op.f('fk_result_outcome_groups_result_outcome_id_result_outcomes')),
    sa.PrimaryKeyConstraint('result_outcome_group_id', name=op.f('pk_result_outcome_groups')),
    schema='clinicaltrials'
    )
    op.create_table('studies',
    sa.Column('study_id', sa.BigInteger(), nullable=False),
    sa.Column('org_study_id', sa.Unicode(), nullable=True),
    sa.Column('secondary_id', sa.Unicode(), nullable=True),
    sa.Column('nct_id', sa.Unicode(), nullable=False),
    sa.Column('brief_title', sa.Unicode(), nullable=False),
    sa.Column('acronym', sa.Unicode(), nullable=True),
    sa.Column('official_title', sa.Unicode(), nullable=True),
    sa.Column('source', sa.Unicode(), nullable=False),
    sa.Column('oversight_info_id', sa.BigInteger(), nullable=True),
    sa.Column('brief_summary', sa.UnicodeText(), nullable=True),
    sa.Column('detailed_description', sa.UnicodeText(), nullable=True),
    sa.Column('overall_status', sa.Enum('ACTIVE_NOT', 'COMPLETED', 'INVITATION', 'NOT_YET', 'RECRUITING', 'SUSPENDED', 'TERMINATED', 'WITHDRAWN', 'AVAILABLE', 'UNAVAILABLE', 'TEMP_UNAVAILABLE', 'APPROVED', 'WITHHELD', 'UNKNOWN', name='overallstatustype'), nullable=False),
    sa.Column('last_known_status', sa.Enum('ACTIVE_NOT', 'COMPLETED', 'INVITATION', 'NOT_YET', 'RECRUITING', 'SUSPENDED', 'TERMINATED', 'WITHDRAWN', 'AVAILABLE', 'UNAVAILABLE', 'TEMP_UNAVAILABLE', 'APPROVED', 'WITHHELD', 'UNKNOWN', name='overallstatustype'), nullable=True),
    sa.Column('why_stopped', sa.Unicode(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('primary_completion_date', sa.Date(), nullable=True),
    sa.Column('verification_date', sa.Date(), nullable=True),
    sa.Column('phase', sa.Enum('NA', 'PHASE_1_EARLY', 'PHASE_1', 'PHASE_1_2', 'PHASE_2', 'PHASE_2_3', 'PHASE_3', 'PHASE_4', name='phasetype'), nullable=False),
    sa.Column('study_type', sa.Enum('EXPANDED', 'INTERVENTIONAL', 'NA', 'OBSERVATIONAL', 'OBSERVATIONAL_PR', name='studytype'), nullable=False),
    sa.Column('expanded_access_info_id', sa.BigInteger(), nullable=True),
    sa.Column('study_design_info_id', sa.BigInteger(), nullable=True),
    sa.Column('target_duration', sa.Unicode(), nullable=True),
    sa.Column('enrollment_id', sa.BigInteger(), nullable=True),
    sa.Column('biospec_retention', sa.Enum('NONE', 'SAMPLES_W_DNA', 'SAMPLES_WO_DNA', name='biospecretentiontype'), nullable=True),
    sa.Column('biospec_description', sa.Unicode(), nullable=True),
    sa.Column('eligibility_id', sa.BigInteger(), nullable=True),
    sa.Column('contact_primary_id', sa.BigInteger(), nullable=True),
    sa.Column('contact_backup_id', sa.BigInteger(), nullable=True),
    sa.Column('study_dates_id', sa.BigInteger(), nullable=False),
    sa.Column('responsible_party_id', sa.BigInteger(), nullable=True),
    sa.Column('patient_data_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['contact_backup_id'], ['clinicaltrials.contacts.contact_id'], name=op.f('fk_studies_contact_backup_id_contacts')),
    sa.ForeignKeyConstraint(['contact_primary_id'], ['clinicaltrials.contacts.contact_id'], name=op.f('fk_studies_contact_primary_id_contacts')),
    sa.ForeignKeyConstraint(['eligibility_id'], ['clinicaltrials.eligibilities.eligibility_id'], name=op.f('fk_studies_eligibility_id_eligibilities')),
    sa.ForeignKeyConstraint(['enrollment_id'], ['clinicaltrials.enrollments.enrollment_id'], name=op.f('fk_studies_enrollment_id_enrollments')),
    sa.ForeignKeyConstraint(['expanded_access_info_id'], ['clinicaltrials.expanded_access_infos.expanded_access_info_id'], name=op.f('fk_studies_expanded_access_info_id_expanded_access_infos')),
    sa.ForeignKeyConstraint(['oversight_info_id'], ['clinicaltrials.oversight_infos.oversight_info_id'], name=op.f('fk_studies_oversight_info_id_oversight_infos')),
    sa.ForeignKeyConstraint(['patient_data_id'], ['clinicaltrials.patient_datas.patient_data_id'], name=op.f('fk_studies_patient_data_id_patient_datas')),
    sa.ForeignKeyConstraint(['responsible_party_id'], ['clinicaltrials.responsible_parties.responsible_party_id'], name=op.f('fk_studies_responsible_party_id_responsible_parties')),
    sa.ForeignKeyConstraint(['study_dates_id'], ['clinicaltrials.study_dates.study_dates_id'], name=op.f('fk_studies_study_dates_id_study_dates')),
    sa.ForeignKeyConstraint(['study_design_info_id'], ['clinicaltrials.study_design_infos.study_design_info_id'], name=op.f('fk_studies_study_design_info_id_study_design_infos')),
    sa.PrimaryKeyConstraint('study_id', name=op.f('pk_studies')),
    sa.UniqueConstraint('nct_id', name=op.f('uq_studies_nct_id')),
    schema='clinicaltrials'
    )
    op.create_index(op.f('ix_clinicaltrials_studies_biospec_retention'), 'studies', ['biospec_retention'], unique=False, schema='clinicaltrials')
    op.create_index(op.f('ix_clinicaltrials_studies_last_known_status'), 'studies', ['last_known_status'], unique=False, schema='clinicaltrials')
    op.create_index(op.f('ix_clinicaltrials_studies_overall_status'), 'studies', ['overall_status'], unique=False, schema='clinicaltrials')
    op.create_index(op.f('ix_clinicaltrials_studies_phase'), 'studies', ['phase'], unique=False, schema='clinicaltrials')
    op.create_index(op.f('ix_clinicaltrials_studies_study_type'), 'studies', ['study_type'], unique=False, schema='clinicaltrials')
    op.create_table('location_investigators',
    sa.Column('location_investigator_id', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('investigator_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['investigator_id'], ['clinicaltrials.investigators.investigator_id'], name=op.f('fk_location_investigators_investigator_id_investigators')),
    sa.ForeignKeyConstraint(['location_id'], ['clinicaltrials.locations.location_id'], name=op.f('fk_location_investigators_location_id_locations')),
    sa.PrimaryKeyConstraint('location_investigator_id', name=op.f('pk_location_investigators')),
    sa.UniqueConstraint('location_id', 'investigator_id', name=op.f('uq_location_investigators_location_id')),
    schema='clinicaltrials'
    )
    op.create_table('study_aliases',
    sa.Column('study_alias_id', sa.BigInteger(), nullable=False),
    sa.Column('study_id', sa.BigInteger(), nullable=False),
    sa.Column('alias_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['alias_id'], ['clinicaltrials.aliases.alias_id'], name=op.f('fk_study_aliases_alias_id_aliases')),
    sa.ForeignKeyConstraint(['study_id'], ['clinicaltrials.studies.study_id'], name=op.f('fk_study_aliases_study_id_studies')),
    sa.PrimaryKeyConstraint('study_alias_id', name=op.f('pk_study_aliases')),
    sa.UniqueConstraint('study_id', 'alias_id', name=op.f('uq_study_aliases_study_id')),
    schema='clinicaltrials'
    )
    op.create_table('study_arm_groups',
    sa.Column('study_arm_group_id', sa.BigInteger(), nullable=False),
    sa.Column('study_id', sa.BigInteger(), nullable=False),
    sa.Column('arm_group_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['arm_group_id'], ['clinicaltrials.arm_groups.arm_group_id'], name=op.f('fk_study_arm_groups_arm_group_id_arm_groups')),
    sa.ForeignKeyConstraint(['study_id'], ['clinicaltrials.studies.study_id'], name=op.f('fk_study_arm_groups_study_id_studies')),
    sa.PrimaryKeyConstraint('study_arm_group_id', name=op.f('pk_study_arm_groups')),
    sa.UniqueConstraint('study_id', 'arm_group_id', name=op.f('uq_study_arm_groups_study_id')),
    schema='clinicaltrials'
    )
    op.create_table('study_conditions',
    sa.Column('study_condition_id', sa.BigInteger(), nullable=False),
    sa.Column('study_id', sa.BigInteger(), nullable=False),
    sa.Column('condition_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['clinicaltrials.conditions.condition_id'], name=op.f('fk_study_conditions_condition_id_conditions')),
    sa.ForeignKeyConstraint(['study_id'], ['clinicaltrials.studies.study_id'], name=op.f('fk_study_conditions_study_id_studies')),
    sa.PrimaryKeyConstraint('study_condition_id', name=op.f('pk_study_conditions')),
    sa.UniqueConstraint('study_id', 'condition_id', name=op.f('uq_study_conditions_study_id')),
    schema='clinicaltrials'
    )
    op.create_table('study_interventions',
    sa.Column('study_intervention_id', sa.BigInteger(), nullable=False),
    sa.Column('study_id', sa.BigInteger(), nullable=False),
    sa.Column('intervention_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['intervention_id'], ['clinicaltrials.interventions.intervention_id'], name=op.f('fk_study_interventions_intervention_id_interventions')),
    sa.ForeignKeyConstraint(['study_id'], ['clinicaltrials.studies.study_id'], name=op.f('fk_study_interventions_study_id_studies')),
    sa.PrimaryKeyConstraint('study_intervention_id', name=op.f('pk_study_interventions')),
    sa.UniqueConstraint('study_id', 'intervention_id', name=op.f('uq_study_interventions_study_id')),
    schema='clinicaltrials'
    )
    op.create_table('study_investigators',
    sa.Column('study_investigator_id', sa.BigInteger(), nullable=False),
    sa.Column('study_id', sa.BigInteger(), nullable=False),
    sa.Column('investigator_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['investigator_id'], ['clinicaltrials.investigators.investigator_id'], name=op.f('fk_study_investigators_investigator_id_investigators')),
    sa.ForeignKeyConstraint(['study_id'], ['clinicaltrials.studies.study_id'], name=op.f('fk_study_investigators_study_id_studies')),
    sa.PrimaryKeyConstraint('study_investigator_id', name=op.f('pk_study_investigators')),
    sa.UniqueConstraint('study_id', 'investigator_id', name=op.f('uq_study_investigators_study_id')),
    schema='clinicaltrials'
    )
    op.create_table('study_keywords',
    sa.Column('study_keyword_id', sa.BigInteger(), nullable=False),
    sa.Column('study_id', sa.BigInteger(), nullable=False),
    sa.Column('keyword_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['clinicaltrials.keywords.keyword_id'], name=op.f('fk_study_keywords_keyword_id_keywords')),
    sa.ForeignKeyConstraint(['study_id'], ['clinicaltrials.studies.study_id'], name=op.f('fk_study_keywords_study_id_studies')),
    sa.PrimaryKeyConstraint('study_keyword_id', name=op.f('pk_study_keywords')),
    sa.UniqueConstraint('study_id', 'keyword_id', name=op.f('uq_study_keywords_study_id')),
    schema='clinicaltrials'
    )
    op.create_table('study_locations',
    sa.Column('study_location_id', sa.BigInteger(), nullable=False),
    sa.Column('study_id', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['clinicaltrials.locations.location_id'], name=op.f('fk_study_locations_location_id_locations')),
    sa.ForeignKeyConstraint(['study_id'], ['clinicaltrials.studies.study_id'], name=op.f('fk_study_locations_study_id_studies')),
    sa.PrimaryKeyConstraint('study_location_id', name=op.f('pk_study_locations')),
    sa.UniqueConstraint('study_id', 'location_id', name=op.f('uq_study_locations_study_id')),
    schema='clinicaltrials'
    )
    op.create_table('study_mesh_terms',
    sa.Column('study_mesh_term_id', sa.BigInteger(), nullable=False),
    sa.Column('study_id', sa.BigInteger(), nullable=False),
    sa.Column('mesh_term_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('CONDITION', 'INTERVENTION', name='meshtermtype'), nullable=False),
    sa.ForeignKeyConstraint(['mesh_term_id'], ['clinicaltrials.mesh_terms.mesh_term_id'], name=op.f('fk_study_mesh_terms_mesh_term_id_mesh_terms')),
    sa.ForeignKeyConstraint(['study_id'], ['clinicaltrials.studies.study_id'], name=op.f('fk_study_mesh_terms_study_id_studies')),
    sa.PrimaryKeyConstraint('study_mesh_term_id', name=op.f('pk_study_mesh_terms')),
    sa.UniqueConstraint('study_id', 'mesh_term_id', name=op.f('uq_study_mesh_terms_study_id')),
    schema='clinicaltrials'
    )
    op.create_index(op.f('ix_clinicaltrials_study_mesh_terms_type'), 'study_mesh_terms', ['type'], unique=False, schema='clinicaltrials')
    op.create_table('study_outcomes',
    sa.Column('study_primary_outcome_id', sa.BigInteger(), nullable=False),
    sa.Column('study_id', sa.BigInteger(), nullable=False),
    sa.Column('protocol_outcome_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('PRIMARY', 'SECONDARY', 'POST_HOC', 'OTHER', name='outcometype'), nullable=False),
    sa.ForeignKeyConstraint(['protocol_outcome_id'], ['clinicaltrials.protocol_outcomes.protocol_outcome_id'], name=op.f('fk_study_outcomes_protocol_outcome_id_protocol_outcomes')),
    sa.ForeignKeyConstraint(['study_id'], ['clinicaltrials.studies.study_id'], name=op.f('fk_study_outcomes_study_id_studies')),
    sa.PrimaryKeyConstraint('study_primary_outcome_id', name=op.f('pk_study_outcomes')),
    sa.UniqueConstraint('study_id', 'protocol_outcome_id', name=op.f('uq_study_outcomes_study_id')),
    schema='clinicaltrials'
    )
    op.create_index(op.f('ix_clinicaltrials_study_outcomes_type'), 'study_outcomes', ['type'], unique=False, schema='clinicaltrials')
    op.create_table('study_references',
    sa.Column('study_reference_id', sa.BigInteger(), nullable=False),
    sa.Column('study_id', sa.BigInteger(), nullable=False),
    sa.Column('reference_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('STANDARD', 'RESULTS', name='referencetype'), nullable=False),
    sa.ForeignKeyConstraint(['reference_id'], ['clinicaltrials.references.reference_id'], name=op.f('fk_study_references_reference_id_references')),
    sa.ForeignKeyConstraint(['study_id'], ['clinicaltrials.studies.study_id'], name=op.f('fk_study_references_study_id_studies')),
    sa.PrimaryKeyConstraint('study_reference_id', name=op.f('pk_study_references')),
    sa.UniqueConstraint('study_id', 'reference_id', name=op.f('uq_study_references_study_id')),
    schema='clinicaltrials'
    )
    op.create_index(op.f('ix_clinicaltrials_study_references_type'), 'study_references', ['type'], unique=False, schema='clinicaltrials')
    op.create_table('study_sponsors',
    sa.Column('study_sponsor_id', sa.BigInteger(), nullable=False),
    sa.Column('study_id', sa.BigInteger(), nullable=False),
    sa.Column('sponsor_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('LEAD', 'COLLABORATOR', name='sponsortype'), nullable=False),
    sa.ForeignKeyConstraint(['sponsor_id'], ['clinicaltrials.sponsors.sponsor_id'], name=op.f('fk_study_sponsors_sponsor_id_sponsors')),
    sa.ForeignKeyConstraint(['study_id'], ['clinicaltrials.studies.study_id'], name=op.f('fk_study_sponsors_study_id_studies')),
    sa.PrimaryKeyConstraint('study_sponsor_id', name=op.f('pk_study_sponsors')),
    sa.UniqueConstraint('study_id', 'sponsor_id', name=op.f('uq_study_sponsors_study_id')),
    schema='clinicaltrials'
    )
    op.create_index(op.f('ix_clinicaltrials_study_sponsors_type'), 'study_sponsors', ['type'], unique=False, schema='clinicaltrials')
    op.create_table('study_study_docs',
    sa.Column('study_study_doc_id', sa.BigInteger(), nullable=False),
    sa.Column('study_id', sa.BigInteger(), nullable=False),
    sa.Column('study_doc_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['study_doc_id'], ['clinicaltrials.study_docs.study_doc_id'], name=op.f('fk_study_study_docs_study_doc_id_study_docs')),
    sa.ForeignKeyConstraint(['study_id'], ['clinicaltrials.studies.study_id'], name=op.f('fk_study_study_docs_study_id_studies')),
    sa.PrimaryKeyConstraint('study_study_doc_id', name=op.f('pk_study_study_docs')),
    sa.UniqueConstraint('study_id', 'study_doc_id', name=op.f('uq_study_study_docs_study_id')),
    schema='clinicaltrials'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_study_docs', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_study_sponsors_type'), table_name='study_sponsors', schema='clinicaltrials')
    op.drop_table('study_sponsors', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_study_references_type'), table_name='study_references', schema='clinicaltrials')
    op.drop_table('study_references', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_study_outcomes_type'), table_name='study_outcomes', schema='clinicaltrials')
    op.drop_table('study_outcomes', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_study_mesh_terms_type'), table_name='study_mesh_terms', schema='clinicaltrials')
    op.drop_table('study_mesh_terms', schema='clinicaltrials')
    op.drop_table('study_locations', schema='clinicaltrials')
    op.drop_table('study_keywords', schema='clinicaltrials')
    op.drop_table('study_investigators', schema='clinicaltrials')
    op.drop_table('study_interventions', schema='clinicaltrials')
    op.drop_table('study_conditions', schema='clinicaltrials')
    op.drop_table('study_arm_groups', schema='clinicaltrials')
    op.drop_table('study_aliases', schema='clinicaltrials')
    op.drop_table('location_investigators', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_studies_study_type'), table_name='studies', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_studies_phase'), table_name='studies', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_studies_overall_status'), table_name='studies', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_studies_last_known_status'), table_name='studies', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_studies_biospec_retention'), table_name='studies', schema='clinicaltrials')
    op.drop_table('studies', schema='clinicaltrials')
    op.drop_table('result_outcome_groups', schema='clinicaltrials')
    op.drop_table('reported_event_groups', schema='clinicaltrials')
    op.drop_table('milestone_participants', schema='clinicaltrials')
    op.drop_table('measure_category_measurements', schema='clinicaltrials')
    op.drop_table('measure_analyzed_counts', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_locations_status'), table_name='locations', schema='clinicaltrials')
    op.drop_table('locations', schema='clinicaltrials')
    op.drop_table('event_event_counts', schema='clinicaltrials')
    op.drop_table('result_outcomes', schema='clinicaltrials')
    op.drop_table('reported_events', schema='clinicaltrials')
    op.drop_table('period_milestones', schema='clinicaltrials')
    op.drop_table('period_drop_withdraw_reasons', schema='clinicaltrials')
    op.drop_table('participants', schema='clinicaltrials')
    op.drop_table('participant_flow_periods', schema='clinicaltrials')
    op.drop_table('participant_flow_groups', schema='clinicaltrials')
    op.drop_table('measurements', schema='clinicaltrials')
    op.drop_table('measure_measure_classes', schema='clinicaltrials')
    op.drop_table('measure_measure_analyzeds', schema='clinicaltrials')
    op.drop_table('measure_counts', schema='clinicaltrials')
    op.drop_table('measure_class_categories', schema='clinicaltrials')
    op.drop_table('measure_class_analyzeds', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_investigators_role'), table_name='investigators', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_investigators_md5'), table_name='investigators', schema='clinicaltrials')
    op.drop_table('investigators', schema='clinicaltrials')
    op.drop_table('intervention_arm_groups', schema='clinicaltrials')
    op.drop_table('intervention_aliases', schema='clinicaltrials')
    op.drop_table('event_list_categories', schema='clinicaltrials')
    op.drop_table('event_counts', schema='clinicaltrials')
    op.drop_table('event_category_events', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_contacts_md5'), table_name='contacts', schema='clinicaltrials')
    op.drop_table('contacts', schema='clinicaltrials')
    op.drop_table('baseline_measures', schema='clinicaltrials')
    op.drop_table('baseline_measure_analyzeds', schema='clinicaltrials')
    op.drop_table('baseline_groups', schema='clinicaltrials')
    op.drop_table('analysis_groups')
    op.drop_table('study_docs', schema='clinicaltrials')
    op.drop_table('study_design_infos', schema='clinicaltrials')
    op.drop_table('study_dates', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_sponsors_md5'), table_name='sponsors', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_sponsors_class'), table_name='sponsors', schema='clinicaltrials')
    op.drop_table('sponsors', schema='clinicaltrials')
    op.drop_table('responsible_parties', schema='clinicaltrials')
    op.drop_table('references', schema='clinicaltrials')
    op.drop_table('protocol_outcomes', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_persons_md5'), table_name='persons', schema='clinicaltrials')
    op.drop_table('persons', schema='clinicaltrials')
    op.drop_table('periods', schema='clinicaltrials')
    op.drop_table('patient_datas', schema='clinicaltrials')
    op.drop_table('participant_flows', schema='clinicaltrials')
    op.drop_table('oversight_infos', schema='clinicaltrials')
    op.drop_table('milestones', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_mesh_terms_md5'), table_name='mesh_terms', schema='clinicaltrials')
    op.drop_table('mesh_terms', schema='clinicaltrials')
    op.drop_table('measures', schema='clinicaltrials')
    op.drop_table('measure_classes', schema='clinicaltrials')
    op.drop_table('measure_categories', schema='clinicaltrials')
    op.drop_table('measure_analyzeds', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_keywords_md5'), table_name='keywords', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_keywords_keyword'), table_name='keywords', schema='clinicaltrials')
    op.drop_table('keywords', schema='clinicaltrials')
    op.drop_table('interventions', schema='clinicaltrials')
    op.drop_table('groups', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_facilities_md5'), table_name='facilities', schema='clinicaltrials')
    op.drop_table('facilities', schema='clinicaltrials')
    op.drop_table('expanded_access_infos', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_events_assessment'), table_name='events', schema='clinicaltrials')
    op.drop_table('events', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_event_lists_default_assessment'), table_name='event_lists', schema='clinicaltrials')
    op.drop_table('event_lists', schema='clinicaltrials')
    op.drop_table('event_categories', schema='clinicaltrials')
    op.drop_table('enrollments', schema='clinicaltrials')
    op.drop_table('eligibilities', schema='clinicaltrials')
    op.drop_table('drop_withdraw_reasons', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_conditions_md5'), table_name='conditions', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_conditions_condition'), table_name='conditions', schema='clinicaltrials')
    op.drop_table('conditions', schema='clinicaltrials')
    op.drop_table('baselines', schema='clinicaltrials')
    op.drop_table('arm_groups', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_analyses_non_inferiority_type'), table_name='analyses', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_analyses_dispersion_type'), table_name='analyses', schema='clinicaltrials')
    op.drop_table('analyses', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_aliases_md5'), table_name='aliases', schema='clinicaltrials')
    op.drop_table('aliases', schema='clinicaltrials')
    # ### end Alembic commands ###
