"""empty message

Revision ID: 5634170b31c8
Revises: 59e536660f71
Create Date: 2018-04-05 03:09:37.660362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5634170b31c8'
down_revision = '59e536660f71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('investigators', 'role',
               existing_type=postgresql.ENUM('PRINCIPAL', 'SUB', 'CHAIR', 'DIRECTOR', name='roletype'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('investigators', 'role',
               existing_type=postgresql.ENUM('PRINCIPAL', 'SUB', 'CHAIR', 'DIRECTOR', name='roletype'),
               nullable=False)
    # ### end Alembic commands ###
