"""empty message

Revision ID: 59e536660f71
Revises: 96b2cc0ec684
Create Date: 2018-04-05 02:27:02.882704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59e536660f71'
down_revision = '96b2cc0ec684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('responsible_parties', 'type',
               existing_type=postgresql.ENUM('SPONSOR', 'PRINCIPAL', 'SPONSOR_INVESTIGATOR', name='responsiblepartytype'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('responsible_parties', 'type',
               existing_type=postgresql.ENUM('SPONSOR', 'PRINCIPAL', 'SPONSOR_INVESTIGATOR', name='responsiblepartytype'),
               nullable=False)
    # ### end Alembic commands ###
