"""empty message

Revision ID: 96b2cc0ec684
Revises: 169cb795b730
Create Date: 2018-04-05 02:09:17.026034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96b2cc0ec684'
down_revision = '169cb795b730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('studies', 'enrollment_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('studies', 'enrollment_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
