"""empty message

Revision ID: e83e0f198616
Revises: 5634170b31c8
Create Date: 2018-04-05 03:27:53.312357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e83e0f198616'
down_revision = '5634170b31c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('facilities', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('facilities', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('facilities', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('facilities', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
