---

# PostgreSQL variables

# Define the encrypted SQL password variable outside the nested structures due
# to the issue described in https://stackoverflow
# .com/questions/50770524/ansible-vault-inline-variable-with-to-nice-json
# -unexpected-templating-type-erro
sql_password: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    32336264333131626463313464343231343139383366396530666164363238653861616134313437
    3831616434396435353138383035366666613235326536620a623466303932336639386662663835
    61313565626662353334656639303462613230373330376266353039346231653335636638333932
    3834653761333337380a353762633461326336363839386432323536343832313432326462313462
    31643865313131373966323638636663656637646335383064653434363137626233313865346433
    6233386337306238306265363536633134373131363864316562

# PostgreSQL Server Settings.
postgresql_python_library: "python-psycopg2"

# PostgreSQL Databases.
postgresql_databases:
  - name: "fightfor"
    port: 5432
  - name: "test"
    port: 5432

# PostgreSQL Users.
postgresql_users:
  - name: "{{ system.user }}"
    password: "{{ sql_password }}"
    port: 5432

# PostgreSQL schemata.
postgresql_schemata:
  - clinicaltrials


project:
  name: "ct-ingester"

system:
  # User name.
  user: "ct_ingester"
  # User group.
  group: "ct_ingester"
  # Application directories.
  directories:
    config: "/etc/{{ project.name }}"
    share: "/usr/local/share/{{ project.name }}"
    run: "/var/run/{{ project.name }}"
    log: "/var/log/{{ project.name }}"
    virtual_env: "/usr/local/share/{{ project.name }}/venvs/{{ project.name }}"

# Application Configuration Settings.
config:
  test:
    # General Settings.
    logger_level: DEBUG

    # PostgreSQL Server Configuration Settings.
    sql_host: "localhost"
    sql_port: 5432
    sql_username: "{{ system.user }}"
    sql_password: "{{ sql_password }}"
    sql_db: "test"

    # Gunicorn Configuration Settings.
    gunicorn:
      host: "127.0.0.1"
      port: 5555
      workers: 1
      worker_class: sync

  dev:
    # General Settings.
    logger_level: DEBUG

    # PostgreSQL Server Configuration Settings.
    sql_host: "localhost"
    sql_port: 5432
    sql_username: "{{ system.user }}"
    sql_password: "{{ sql_password }}"
    sql_db: "fightfor"

    # Gunicorn Configuration Settings.
    gunicorn:
      host: "127.0.0.1"
      port: 5555
      workers: 1
      worker_class: sync

  prod:
    # General Settings.
    logger_level: INFO

    # PostgreSQL Server Configuration Settings.
    sql_host: "localhost"
    sql_port: 5432
    sql_username: "{{ system.user }}"
    sql_password: "{{ sql_password }}"
    sql_db: "fightfor"

    # Gunicorn Configuration Settings.
    gunicorn:
      host: "127.0.0.1"
      port: 5555
      workers: 4
      worker_class: sync
